name: Deploy Next.js CI/CD


on: 
  push:
    branches: [ main ]
    
jobs:
  build:
    
    runs-on: self-hosted
    
    strategy:
       matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
  # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run export
    - run: sudo rm -r /var/www/codeconnect.ca/html/*
    - run: sudo mv /home/ubuntu/actions-runner/Cody-Connect-Next/Cody-Connecty-Next/Cody-Connecty-Next/out/* /var/www/codeconnect.ca/html 
