name: Deploy Next.js CI/CD

on: 
  push:
    branches: [ main ]
    
jobs:
  build:
    
    runs-on: self-hosted
    
    strategy:
       matrix:
        node-version: [10.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: npm run export
    - run: rm -r /var/www/codeconnect.ca/html
    - run: mv /home/ubuntu/actions-runner/Cody-Connect-Next/Cody-Connecty-Next/Cody-Connecty-Next/out/* /var/www/codeconnect.ca/html 
